server:
  port: 9003 #内置tomcat启动的端口号(集群需不同名)

eureka:
  instance:
    prefer-ip-address: true  # 访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10
    instance-id: 127.0.0.1:9003   #显示服务名称(ip:port集群需不同名,如果重复会覆盖之前的实例)
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: websocket
  rocketmq:
        #name-server: 127.0.0.1:9876
        name-server: 10.9.216.1:9876
        producer-send-msg-timeout: 3000
        producer-group-name: websocket-127-0-0-1-9003
  redis:
      host: 10.9.216.1
      #host: 127.0.0.1
      port: 6379
      timeout: 3000ms
      jedis:
        pool:
          max-active: 20
          max-idle: 8
          min-idle: 0
management:
  endpoints:
    jmx:
      exposure:
        include: health,info
        exclude:


