server:
  port: 8001
spring:
  application:
    name: portal
  redis:
      #host: 127.0.0.1
      host: 192.168.99.100
      port: 6379
      timeout: 1000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

